<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDDs8cIs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDDs8cIs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDDs8cIs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDDs8cIs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDDs8cIs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DDs8cIs',
    'container.build_id' => '25e53c3f',
    'container.build_time' => 1649287327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDDs8cIs');
